import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer";

const inter = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
